eureka:
  instance:
    hostname:  localhost
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

server:
  port: 8082
spring:
  application:
    name: students
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/students
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
